theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.soft-wrap]
enable = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
C-h = "move_char_left"
C-l = "move_char_right"
C-j = "move_visual_line_down"
C-k = "move_visual_line_up"

[keys.normal]
up = "remove_primary_selection"
down = "copy_selection_on_next_line"
S-tab = ":bp"
tab = ":bn"
C-s = [":fmt" ,":w"]
esc = ["collapse_selection", "keep_primary_selection"]

q = "move_prev_word_start"
C-u =[ "half_page_up","goto_window_center"]
C-d =[ "half_page_down","goto_window_center"]

C-j = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
C-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
p = ":clipboard-paste-after"
y = ":clipboard-yank"
q = "extend_prev_word_start"
C-down = ["delete_selection", "paste_after" ]
C-up = ["delete_selection", "move_line_up", "paste_before" ]

